// De-duplicated ticker list sourced from Vanguard holdings + S&P 500 constituents
// ~580 unique tickers after cleanup. BRK/B excluded (slash in symbol causes issues).

export const TICKER_LIST: string[] = [
    'AAPL', 'ABBV', 'ABT', 'ACN', 'ADBE', 'ADI', 'ADM', 'ADP', 'ADSK', 'AEE',
    'AEP', 'AES', 'AFL', 'AIG', 'AIZ', 'AJG', 'AKAM', 'ALB', 'ALGN', 'ALL',
    'ALLE', 'ALSN', 'AMAT', 'AMD', 'AME', 'AMGN', 'AMH', 'AMT', 'AMZN', 'AN',
    'ANET', 'ANSS', 'AON', 'AOS', 'APA', 'APD', 'APH', 'APO', 'APTV', 'ARE',
    'ARES', 'ARMK', 'ATO', 'AVB', 'AVGO', 'AVY', 'AWK', 'AXON', 'AXP', 'AZO',
    'BA', 'BAC', 'BAH', 'BAX', 'BBWI', 'BBY', 'BDX', 'BEN', 'BG', 'BIIB',
    'BIO', 'BK', 'BKR', 'BLD', 'BLDR', 'BLK', 'BMRN', 'BMY', 'BR', 'BRO',
    'BSX', 'BWA', 'BXP', 'BX', 'C', 'CAG', 'CAH', 'CAT', 'CB', 'CBOE',
    'CBRE', 'CCI', 'CCK', 'CCL', 'CDNS', 'CDW', 'CE', 'CEG', 'CF', 'CFG',
    'CHD', 'CHDN', 'CHE', 'CHRW', 'CHTR', 'CI', 'CINF', 'CL', 'CLF', 'CLH',
    'CLX', 'CMA', 'CMCSA', 'CME', 'CMG', 'CMI', 'CMS', 'CNC', 'CNP', 'COF',
    'COO', 'COP', 'COST', 'CPB', 'CPNG', 'CPRT', 'CPT', 'CRM', 'CRL', 'CSCO',
    'CSGP', 'CSL', 'CSX', 'CTAS', 'CTRA', 'CTSH', 'CTVA', 'CVNA', 'CVS', 'CVX',
    'CZR', 'D', 'DAL', 'DAR', 'DASH', 'DCI', 'DDOG', 'DE', 'DECK', 'DELL',
    'DG', 'DHI', 'DHR', 'DINO', 'DIS', 'DKS', 'DLR', 'DLTR', 'DOV', 'DOW',
    'DRI', 'DT', 'DTE', 'DUK', 'DVA', 'DVN', 'DXCM', 'EA', 'EBAY', 'ECL',
    'ED', 'EFX', 'EIX', 'EL', 'ELS', 'EMN', 'EMR', 'EOG', 'EPAM', 'EPR',
    'EQH', 'EQR', 'EQT', 'EQIX', 'ES', 'ESS', 'ETN', 'ETR', 'EVR', 'EVRG',
    'EW', 'EWBC', 'EXAS', 'EXC', 'EXPD', 'EXPE', 'EXR', 'F', 'FAST', 'FCN',
    'FCX', 'FDX', 'FE', 'FERG', 'FICO', 'FIS', 'FITB', 'FIVE', 'FIX', 'FLS',
    'FMC', 'FND', 'FOXA', 'FOX', 'FR', 'FRT', 'FSLR', 'FTI', 'FTNT', 'FV',
    'G', 'GD', 'GE', 'GEHC', 'GEN', 'GEV', 'GGG', 'GILD', 'GIS', 'GL',
    'GLPI', 'GLW', 'GM', 'GMED', 'GNRC', 'GPC', 'GPN', 'GRMN', 'GS', 'GWW',
    'H', 'HAL', 'HAS', 'HBAN', 'HCA', 'HD', 'HES', 'HIG', 'HLT', 'HOLX',
    'HON', 'HPE', 'HPQ', 'HRL', 'HSIC', 'HSY', 'HUBB', 'HUM', 'HWM', 'HXL',
    'IBM', 'ICE', 'ICLR', 'IDXX', 'IEX', 'IFF', 'ILMN', 'INCY', 'INTC', 'INTU',
    'IONS', 'IP', 'IPG', 'IQV', 'IR', 'IRDM', 'IRM', 'ISRG', 'IT', 'ITW',
    'J', 'JAZZ', 'JBHT', 'JBL', 'JCI', 'JEF', 'JHG', 'JKHY', 'JNJ', 'JPM',
    'K', 'KDP', 'KEY', 'KEYS', 'KHC', 'KIM', 'KKR', 'KLAC', 'KMB', 'KMI',
    'KRC', 'KR', 'L', 'LAMR', 'LDOS', 'LEN', 'LH', 'LHX', 'LIN', 'LKQ',
    'LLY', 'LMT', 'LNC', 'LNT', 'LOW', 'LPLA', 'LPX', 'LRCX', 'LSCC', 'LSTR',
    'LULU', 'LUV', 'LVS', 'LW', 'LYB', 'LYV', 'M', 'MA', 'MAR', 'MAS',
    'MCD', 'MCHP', 'MCK', 'MCO', 'MDB', 'MDLZ', 'MDT', 'MET', 'MGM', 'MHK',
    'MKC', 'MKTX', 'MLI', 'MLM', 'MMC', 'MMM', 'MNDY', 'MNR', 'MO', 'MOH',
    'MOS', 'MPC', 'MPWR', 'MRK', 'MRNA', 'MRO', 'MRVL', 'MS', 'MSCI', 'MSFT',
    'MSI', 'MTB', 'MTCH', 'MTD', 'MTG', 'MTN', 'MTZ', 'MU', 'MUSA', 'NCLH',
    'NDAQ', 'NDSN', 'NEE', 'NEM', 'NET', 'NFLX', 'NI', 'NKE', 'NOC', 'NOV',
    'NOW', 'NRG', 'NSC', 'NTAP', 'NTRS', 'NUE', 'NU', 'NVDA', 'NVR', 'NVT',
    'NWL', 'NXST', 'O', 'ODFL', 'OKE', 'OLED', 'OLN', 'OMC', 'ON', 'ORCL',
    'ORI', 'OSK', 'OTIS', 'OXY', 'PANW', 'PARA', 'PAYC', 'PAYX', 'PCAR', 'PCG',
    'PCTY', 'PDD', 'PEG', 'PENN', 'PEP', 'PFE', 'PFG', 'PG', 'PGR', 'PH',
    'PHM', 'PINS', 'PLD', 'PLTR', 'PM', 'PNC', 'PNR', 'PNW', 'POOL', 'PPC',
    'PPG', 'PPL', 'PRGO', 'PRU', 'PSA', 'PSX', 'PTC', 'PWR', 'PYPL', 'QCOM',
    'QRVO', 'R', 'RCL', 'REG', 'REGN', 'RF', 'RHI', 'RJF', 'RL', 'RMD',
    'RNR', 'ROL', 'ROP', 'ROST', 'RPM', 'RRX', 'RS', 'RSG', 'RTX', 'RVTY',
    'RYN', 'SAIA', 'SBAC', 'SBUX', 'SCHW', 'SCI', 'SEIC', 'SF', 'SFM', 'SHW',
    'SJM', 'SKX', 'SLB', 'SMCI', 'SMG', 'SNA', 'SNPS', 'SNV', 'SNX', 'SO',
    'SOFI', 'SPG', 'SPGI', 'SPOT', 'SRE', 'SSD', 'ST', 'STE', 'STLD', 'STT',
    'STWD', 'STZ', 'SW', 'SWK', 'SWKS', 'SYK', 'SYY', 'T', 'TAP', 'TDG',
    'TDY', 'TECH', 'TEL', 'TER', 'TFC', 'TFX', 'TGT', 'TJX', 'TMO', 'TMUS',
    'TNL', 'TOL', 'TPR', 'TRGP', 'TROW', 'TRU', 'TRV', 'TSCO', 'TSLA', 'TSN',
    'TT', 'TTD', 'TTEK', 'TTWO', 'TXN', 'TXRH', 'TYL', 'UAL', 'UBER', 'UDR',
    'UHS', 'ULTA', 'UNH', 'UNM', 'UNP', 'UPS', 'URI', 'USB', 'V', 'VFC',
    'VICI', 'VLO', 'VMC', 'VNO', 'VRSK', 'VRSN', 'VRT', 'VRTX', 'VST', 'VTR',
    'VZ', 'W', 'WAB', 'WAT', 'WBA', 'WBD', 'WCC', 'WDC', 'WEC', 'WELL',
    'WEX', 'WFC', 'WHR', 'WING', 'WM', 'WMB', 'WMT', 'WPC', 'WRB', 'WSM',
    'WSO', 'WST', 'WTW', 'WY', 'WYNN', 'XEL', 'XOM', 'XPO', 'XYL', 'YUM',
    'Z', 'ZBH', 'ZBRA', 'ZION', 'ZS', 'ZTS', 'GOOGL', 'GOOG', 'META', 'KO',
    'BKNG', 'APP', 'CRWD', 'ABNB', 'ALNY', 'LNG', 'CARR', 'WDAY', 'AMP',
    'COR', 'FLUT', 'ORLY', 'HOOD', 'RBLX', 'SNOW', 'ELV', 'FI', 'CRH',
    'MSTR', 'COIN',
];
